### ISSUE TITLE
Return to Elements list from Earth fails

### ISSUE THREAD

**Issue by GideonMarsh** [GideonMarsh/Elemental#5]
After viewing the information for the element "earth" on the elements list, selecting return to elements list instead returns the user to the Elements main menu.

Steps to trigger bug: From elements list, select earth element. Then select return to elements list
Expected output: Elements list displayed
Actual output: Main menu screen displayed

**Comment by TimsterMon** [comment]
link will now bring up the elements list page instead of the main index page
